name: Unit Tests

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.1
      - name: Execute Gradle Test
        run: ./gradlew test
